blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.com/aburd/beats-with-friends/issues/new?template=bug.md
    about: Please ask and answer questions here.
